[package]
name = "game_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { default-features = false, version = "0.35.2", features = [
  "ttf",
  "image",
  "gfx",
  "mixer",
] }
anyhow = { version = "1.0.95" }
